SELECT RLCLS.ROLENAME,
RLCLS.CLASSID PERMISSION_LIST,
AUTH.MENUNAME,
AUTH.BARITEMNAME,
AUTH.PNLITEMNAME PAGE_NAME,
CASE AUTH.DISPLAYONLY
WHEN 0 THEN 'UPDATE_ACCESS'
WHEN 1 THEN 'DISPLAY ONLY ACCESS'
END
ACCESS_TYPE,
AUTH.DISPLAYONLY
FROM PSROLECLASS RLCLS,
PSAUTHITEM AUTH,
PSMENUITEM MNU,
PSPNLGROUP PNLGRP
WHERE     RLCLS.CLASSID = AUTH.CLASSID
AND AUTH.MENUNAME = MNU.MENUNAME
AND AUTH.BARITEMNAME = MNU.ITEMNAME
AND AUTH.PNLITEMNAME = PNLGRP.ITEMNAME
AND MNU.PNLGRPNAME = PNLGRP.PNLGRPNAME
-- AND AUTH.DISPLAYONLY = 0        -- Update Access, 1 - means display only
AND RLCLS.ROLENAME IN (SELECT DISTINCT ROLENAME
FROM PSROLEUSER) --Check if role is assigned to any user
--AND AUTH.MENUNAME = 'REQUISITION_ITEMS'            --MENUNAYGV E HERE
AND MNU.PNLGRPNAME = 'PC_EMP_SAL_CMP'         -- COMPONENT NAME HERE
AND PNLGRP.PNLNAME = 'PC_EMP_SAL_PAGE'  ;             --PAGE NAME HERE


SELECT * FROM PSROLEDEFN
WHERE ROLENAME=''


SELECT * FROM PSROLEUSER
WHERE ROLEUSER='VP2'
AND ROLENAME ='TEST_SALARY_ROLE'